package com.IOSANgu4.controller;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import com.IOSANgu4.domain.core.IOUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class IOBaseController {

	private IOUser theUser;
	protected final Log logger = LogFactory.getLog(this.getClass());

	public IOUser getUser(){
		Authentication authentication = SecurityContextHolder.getContext()
				.getAuthentication();
		if (authentication != null) {
			Object principal = authentication.getPrincipal();
			if (principal instanceof IOUser) {
				theUser = (IOUser) principal;
				System.out.println("Loggedin user: " + theUser.getUsername());
			}
		}
		return theUser;
	}


}